### ISSUE TITLE
[Bug] After upgrade to 2024.11 display logs gives error

### ISSUE THREAD

**Issue by Jopandrik** [t0bst4r/home-assistant-matter-hub#77]
Dear Tobias,

When viewing the logs in the Add-On details Windows, the following eror is being displayed:

**### ![Matter-Hub-2024-11-07 211102](https://github.com/user-attachments/assets/a79ece30-404e-48f8-9037-e76d03371124)**

This is only a minor problem and the logs can be viewed in Settings/System/Logs/Home-Assistant-Matter-Hub.

**Comment by t0bst4r** [comment]
Yes i have seen this, too. But actually i don't know why. Is it a bug in home assistant?

**Comment by 011V32** [comment]
I also have the version 2024.11 and I don't have this problem...

**Comment by 011V32** [comment]
Some minutes later, I get a similar error 🙈 
![image](https://github.com/user-attachments/assets/2e33d6c1-d7bd-47bb-a243-f4ba1898830f)

**Comment by t0bst4r** [comment]
This is a bug in home assistant in general.
See https://github.com/home-assistant/core/issues/129860

**Comment by Baos65** [comment]
Hi. 
I have the same problem

"Failed to get supervisor logs, e.callApiRaw is not a function"

this was start befor the instalation of upgrade to 2024.11
